export interface DictionaryEntry {
  en: string
  zh: string
}

const dictionary: DictionaryEntry[] = [
  { en: 'hello', zh: '你好' },
  { en: 'hi', zh: '嗨' },
  { en: 'hey', zh: '嘿' },
  { en: 'world', zh: '世界' },
  { en: 'thank you', zh: '谢谢' },
  { en: 'thanks', zh: '谢谢' },
  { en: 'thanks a lot', zh: '非常感谢' },
  { en: 'thank you very much', zh: '非常感谢' },
  { en: 'goodbye', zh: '再见' },
  { en: 'bye', zh: '再见' },
  { en: 'see you', zh: '再见' },
  { en: 'see you later', zh: '稍后见' },
  { en: 'see you tomorrow', zh: '明天见' },
  { en: 'welcome', zh: '欢迎' },
  { en: 'please', zh: '请' },
  { en: 'sorry', zh: '对不起' },
  { en: 'excuse me', zh: '打扰一下' },
  { en: 'yes', zh: '是' },
  { en: 'no', zh: '不' },
  { en: 'ok', zh: '好的' },
  { en: 'okay', zh: '好的' },
  { en: 'name', zh: '名字' },
  { en: 'my name is', zh: '我的名字是' },
  { en: 'what is your name', zh: '你叫什么名字' },
  { en: 'time', zh: '时间' },
  { en: 'day', zh: '天' },
  { en: 'night', zh: '夜晚' },
  { en: 'morning', zh: '早晨' },
  { en: 'afternoon', zh: '下午' },
  { en: 'evening', zh: '晚上' },
  { en: 'week', zh: '周' },
  { en: 'month', zh: '月' },
  { en: 'year', zh: '年' },
  { en: 'today', zh: '今天' },
  { en: 'tomorrow', zh: '明天' },
  { en: 'yesterday', zh: '昨天' },
  { en: 'here', zh: '这里' },
  { en: 'there', zh: '那里' },
  { en: 'everywhere', zh: '到处' },
  { en: 'home', zh: '家' },
  { en: 'work', zh: '工作' },
  { en: 'school', zh: '学校' },
  { en: 'office', zh: '办公室' },
  { en: 'city', zh: '城市' },
  { en: 'country', zh: '国家' },
  { en: 'food', zh: '食物' },
  { en: 'water', zh: '水' },
  { en: 'coffee', zh: '咖啡' },
  { en: 'tea', zh: '茶' },
  { en: 'bread', zh: '面包' },
  { en: 'rice', zh: '米饭' },
  { en: 'meat', zh: '肉' },
  { en: 'fruit', zh: '水果' },
  { en: 'vegetable', zh: '蔬菜' },
  { en: 'apple', zh: '苹果' },
  { en: 'banana', zh: '香蕉' },
  { en: 'orange', zh: '橙子' },
  { en: 'mango', zh: '芒果' },
  { en: 'grape', zh: '葡萄' },
  { en: 'peach', zh: '桃子' },
  { en: 'pear', zh: '梨' },
  { en: 'watermelon', zh: '西瓜' },
  { en: 'strawberry', zh: '草莓' },
  { en: 'blueberry', zh: '蓝莓' },
  { en: 'cherry', zh: '樱桃' },
  { en: 'pineapple', zh: '菠萝' },
  { en: 'coconut', zh: '椰子' },
  { en: 'lemon', zh: '柠檬' },
  { en: 'kiwi', zh: '猕猴桃' },
  { en: 'dragon fruit', zh: '火龙果' },
  { en: 'durian', zh: '榴莲' },
  { en: 'lychee', zh: '荔枝' },
  { en: 'pomegranate', zh: '石榴' },
  { en: 'celery', zh: '芹菜' },
  { en: 'carrot', zh: '胡萝卜' },
  { en: 'potato', zh: '土豆' },
  { en: 'tomato', zh: '西红柿' },
  { en: 'onion', zh: '洋葱' },
  { en: 'garlic', zh: '大蒜' },
  { en: 'broccoli', zh: '西兰花' },
  { en: 'spinach', zh: '菠菜' },
  { en: 'lettuce', zh: '生菜' },
  { en: 'cucumber', zh: '黄瓜' },
  { en: 'eggplant', zh: '茄子' },
  { en: 'pepper', zh: '辣椒' },
  { en: 'corn', zh: '玉米' },
  { en: 'mushroom', zh: '蘑菇' },
  { en: 'tofu', zh: '豆腐' },
  { en: 'milk', zh: '牛奶' },
  { en: 'egg', zh: '鸡蛋' },
  { en: 'fish', zh: '鱼' },
  { en: 'chicken', zh: '鸡肉' },
  { en: 'beef', zh: '牛肉' },
  { en: 'pork', zh: '猪肉' },
  { en: 'lamb', zh: '羊肉' },
  { en: 'shrimp', zh: '虾' },
  { en: 'crab', zh: '螃蟹' },
  { en: 'soup', zh: '汤' },
  { en: 'noodle', zh: '面条' },
  { en: 'dumpling', zh: '饺子' },
  { en: 'cake', zh: '蛋糕' },
  { en: 'cookie', zh: '饼干' },
  { en: 'chocolate', zh: '巧克力' },
  { en: 'ice cream', zh: '冰淇淋' },
  { en: 'yogurt', zh: '酸奶' },
  { en: 'juice', zh: '果汁' },
  { en: 'beer', zh: '啤酒' },
  { en: 'wine', zh: '酒' },
  { en: 'book', zh: '书' },
  { en: 'computer', zh: '电脑' },
  { en: 'phone', zh: '手机' },
  { en: 'internet', zh: '互联网' },
  { en: 'email', zh: '邮件' },
  { en: 'message', zh: '消息' },
  { en: 'friend', zh: '朋友' },
  { en: 'family', zh: '家庭' },
  { en: 'parent', zh: '父母' },
  { en: 'child', zh: '孩子' },
  { en: 'brother', zh: '兄弟' },
  { en: 'sister', zh: '姐妹' },
  { en: 'love', zh: '爱' },
  { en: 'happy', zh: '快乐' },
  { en: 'sad', zh: '悲伤' },
  { en: 'angry', zh: '生气' },
  { en: 'tired', zh: '累' },
  { en: 'hungry', zh: '饿' },
  { en: 'thirsty', zh: '渴' },
  { en: 'hot', zh: '热' },
  { en: 'cold', zh: '冷' },
  { en: 'rain', zh: '雨' },
  { en: 'sun', zh: '太阳' },
  { en: 'snow', zh: '雪' },
  { en: 'wind', zh: '风' },
  { en: 'cloud', zh: '云' },
  { en: 'sky', zh: '天空' },
  { en: 'earth', zh: '地球' },
  { en: 'moon', zh: '月亮' },
  { en: 'star', zh: '星星' },
  { en: 'tree', zh: '树' },
  { en: 'flower', zh: '花' },
  { en: 'plant', zh: '植物' },
  { en: 'animal', zh: '动物' },
  { en: 'dog', zh: '狗' },
  { en: 'cat', zh: '猫' },
  { en: 'bird', zh: '鸟' },
  { en: 'car', zh: '车' },
  { en: 'bus', zh: '公交车' },
  { en: 'train', zh: '火车' },
  { en: 'plane', zh: '飞机' },
  { en: 'ship', zh: '船' },
  { en: 'walk', zh: '走路' },
  { en: 'run', zh: '跑' },
  { en: 'jump', zh: '跳' },
  { en: 'swim', zh: '游泳' },
  { en: 'read', zh: '阅读' },
  { en: 'write', zh: '写作' },
  { en: 'speak', zh: '说话' },
  { en: 'listen', zh: '听' },
  { en: 'see', zh: '看' },
  { en: 'go', zh: '去' },
  { en: 'come', zh: '来' },
  { en: 'get', zh: '得到' },
  { en: 'give', zh: '给' },
  { en: 'make', zh: '做' },
  { en: 'take', zh: '拿' },
  { en: 'put', zh: '放' },
  { en: 'know', zh: '知道' },
  { en: 'think', zh: '思考' },
  { en: 'learn', zh: '学习' },
  { en: 'teach', zh: '教' },
  { en: 'play', zh: '玩' },
  { en: 'eat', zh: '吃' },
  { en: 'drink', zh: '喝' },
  { en: 'sleep', zh: '睡觉' },
  { en: 'live', zh: '住' },
  { en: 'study', zh: '学习' },
  { en: 'travel', zh: '旅行' },
  { en: 'buy', zh: '买' },
  { en: 'sell', zh: '卖' },
  { en: 'help', zh: '帮助' },
  { en: 'need', zh: '需要' },
  { en: 'want', zh: '想要' },
  { en: 'have', zh: '有' },
  { en: 'do', zh: '做' },
  { en: 'can', zh: '能' },
  { en: 'will', zh: '将' },
  { en: 'should', zh: '应该' },
  { en: 'must', zh: '必须' },
  { en: 'may', zh: '可能' },
  { en: 'could', zh: '可以' },
  { en: 'would', zh: '会' },
  { en: 'am', zh: '是' },
  { en: 'is', zh: '是' },
  { en: 'are', zh: '是' },
  { en: 'was', zh: '是' },
  { en: 'were', zh: '是' },
  { en: 'be', zh: '是' },
  { en: 'been', zh: '已经' },
  { en: 'being', zh: '正在' },
  { en: 'a', zh: '一个' },
  { en: 'an', zh: '一个' },
  { en: 'the', zh: '这个' },
  { en: 'this', zh: '这个' },
  { en: 'that', zh: '那个' },
  { en: 'these', zh: '这些' },
  { en: 'those', zh: '那些' },
  { en: 'my', zh: '我的' },
  { en: 'your', zh: '你的' },
  { en: 'his', zh: '他的' },
  { en: 'her', zh: '她的' },
  { en: 'its', zh: '它的' },
  { en: 'our', zh: '我们的' },
  { en: 'their', zh: '他们的' },
  { en: 'what', zh: '什么' },
  { en: 'who', zh: '谁' },
  { en: 'which', zh: '哪个' },
  { en: 'where', zh: '哪里' },
  { en: 'when', zh: '什么时候' },
  { en: 'why', zh: '为什么' },
  { en: 'how', zh: '怎么' },
  { en: 'many', zh: '许多' },
  { en: 'much', zh: '很多' },
  { en: 'some', zh: '一些' },
  { en: 'any', zh: '任何' },
  { en: 'all', zh: '全部' },
  { en: 'each', zh: '每个' },
  { en: 'every', zh: '每一个' },
  { en: 'few', zh: '很少' },
  { en: 'little', zh: '小的' },
  { en: 'more', zh: '更多' },
  { en: 'most', zh: '最多' },
  { en: 'other', zh: '其他' },
  { en: 'another', zh: '另一个' },
  { en: 'first', zh: '第一' },
  { en: 'second', zh: '第二' },
  { en: 'third', zh: '第三' },
  { en: 'last', zh: '最后' },
  { en: 'next', zh: '下一个' },
  { en: 'only', zh: '只有' },
  { en: 'just', zh: '只是' },
  { en: 'now', zh: '现在' },
  { en: 'then', zh: '然后' },
  { en: 'soon', zh: '很快' },
  { en: 'later', zh: '后来' },
  { en: 'never', zh: '从不' },
  { en: 'always', zh: '总是' },
  { en: 'often', zh: '经常' },
  { en: 'sometimes', zh: '有时' },
  { en: 'usually', zh: '通常' },
  { en: 'already', zh: '已经' },
  { en: 'yet', zh: '还' },
  { en: 'still', zh: '仍然' },
  { en: 'also', zh: '也' },
  { en: 'too', zh: '太' },
  { en: 'very', zh: '非常' },
  { en: 'so', zh: '所以' },
  { en: 'such', zh: '这样的' },
  { en: 'enough', zh: '足够' },
  { en: 'great', zh: '伟大的' },
  { en: 'good', zh: '好的' },
  { en: 'bad', zh: '坏的' },
  { en: 'big', zh: '大的' },
  { en: 'small', zh: '小的' },
  { en: 'long', zh: '长的' },
  { en: 'short', zh: '短的' },
  { en: 'high', zh: '高的' },
  { en: 'low', zh: '低的' },
  { en: 'new', zh: '新的' },
  { en: 'old', zh: '旧的' },
  { en: 'young', zh: '年轻的' },
  { en: 'beautiful', zh: '美丽的' },
  { en: 'important', zh: '重要的' },
  { en: 'interesting', zh: '有趣的' },
  { en: 'boring', zh: '无聊的' },
  { en: 'easy', zh: '容易的' },
  { en: 'difficult', zh: '困难的' },
  { en: 'possible', zh: '可能的' },
  { en: 'impossible', zh: '不可能的' },
  { en: 'true', zh: '真实的' },
  { en: 'false', zh: '假的' },
  { en: 'right', zh: '正确的' },
  { en: 'wrong', zh: '错误的' },
  { en: 'same', zh: '相同的' },
  { en: 'different', zh: '不同的' },
  { en: 'but', zh: '但是' },
  { en: 'and', zh: '和' },
  { en: 'or', zh: '或者' },
  { en: 'because', zh: '因为' },
  { en: 'if', zh: '如果' },
  { en: 'when', zh: '当' },
  { en: 'while', zh: '当...时候' },
  { en: 'although', zh: '虽然' },
  { en: 'however', zh: '然而' },
  { en: 'therefore', zh: '因此' },
  { en: 'moreover', zh: '此外' },
  { en: 'in addition', zh: '另外' },
  { en: 'for example', zh: '例如' },
  { en: 'such as', zh: '例如' },
  { en: 'first of all', zh: '首先' },
  { en: 'to sum up', zh: '总结' },
  { en: 'in conclusion', zh: '总之' },
  { en: 'as a result', zh: '结果' },
  { en: 'consequently', zh: '因此' },
  { en: 'meanwhile', zh: '同时' },
  { en: 'finally', zh: '最后' },
  { en: 'quickly', zh: '快速地' },
  { en: 'slowly', zh: '慢慢地' },
  { en: 'carefully', zh: '小心地' },
  { en: 'completely', zh: '完全地' },
  { en: 'approximately', zh: '大约' },
  { en: 'exactly', zh: '确切地' },
  { en: 'nearly', zh: '几乎' },
  { en: 'almost', zh: '几乎' },
  { en: 'certainly', zh: '当然' },
  { en: 'definitely', zh: '肯定' },
  { en: 'absolutely', zh: '绝对' },
  { en: 'possibly', zh: '可能' },
  { en: 'probably', zh: '大概' },
  { en: 'perhaps', zh: '也许' },
  { en: 'maybe', zh: '也许' },
  { en: 'certain', zh: '确定的' },
  { en: 'sure', zh: '确定的' },
  { en: 'familiar', zh: '熟悉的' },
  { en: 'unfamiliar', zh: '不熟悉的' },
  { en: 'famous', zh: '著名的' },
  { en: 'popular', zh: '流行的' },
  { en: 'common', zh: '常见的' },
  { en: 'rare', zh: '稀有的' },
  { en: 'unique', zh: '独特的' },
  { en: 'special', zh: '特别的' },
  { en: 'ordinary', zh: '普通的' },
  { en: 'simple', zh: '简单的' },
  { en: 'complex', zh: '复杂的' },
  { en: 'obvious', zh: '明显的' },
  { en: 'clear', zh: '清楚的' },
  { en: 'vague', zh: '模糊的' },
  { en: 'precise', zh: '精确的' },
  { en: 'accurate', zh: '准确的' },
  { en: 'support', zh: '支持' },
  { en: 'oppose', zh: '反对' },
  { en: 'agree', zh: '同意' },
  { en: 'disagree', zh: '不同意' },
  { en: 'accept', zh: '接受' },
  { en: 'refuse', zh: '拒绝' },
  { en: 'allow', zh: '允许' },
  { en: 'forbid', zh: '禁止' },
  { en: 'control', zh: '控制' },
  { en: 'manage', zh: '管理' },
  { en: 'handle', zh: '处理' },
  { en: 'solve', zh: '解决' },
  { en: 'improve', zh: '改进' },
  { en: 'develop', zh: '发展' },
  { en: 'increase', zh: '增加' },
  { en: 'decrease', zh: '减少' },
  { en: 'rise', zh: '上升' },
  { en: 'fall', zh: '下降' },
  { en: 'continue', zh: '继续' },
  { en: 'stop', zh: '停止' },
  { en: 'start', zh: '开始' },
  { en: 'begin', zh: '开始' },
  { en: 'end', zh: '结束' },
  { en: 'finish', zh: '完成' },
  { en: 'complete', zh: '完成' },
  { en: 'achieve', zh: '实现' },
  { en: 'reach', zh: '到达' },
  { en: 'gain', zh: '获得' },
  { en: 'obtain', zh: '获得' },
  { en: 'receive', zh: '收到' },
  { en: 'collect', zh: '收集' },
  { en: 'build', zh: '建造' },
  { en: 'create', zh: '创建' },
  { en: 'produce', zh: '生产' },
  { en: 'design', zh: '设计' },
  { en: 'invent', zh: '发明' },
  { en: 'discover', zh: '发现' },
  { en: 'find', zh: '找到' },
  { en: 'search', zh: '搜索' },
  { en: 'explore', zh: '探索' },
  { en: 'investigate', zh: '调查' },
  { en: 'analyze', zh: '分析' },
  { en: 'evaluate', zh: '评估' },
  { en: 'calculate', zh: '计算' },
  { en: 'estimate', zh: '估计' },
  { en: 'predict', zh: '预测' },
  { en: 'expect', zh: '期望' },
  { en: 'hope', zh: '希望' },
  { en: 'wish', zh: '愿望' },
  { en: 'plan', zh: '计划' },
  { en: 'intend', zh: '打算' },
  { en: 'aim', zh: '目标' },
  { en: 'target', zh: '目标' },
  { en: 'goal', zh: '目标' },
  { en: 'task', zh: '任务' },
  { en: 'duty', zh: '职责' },
  { en: 'responsibility', zh: '责任' },
  { en: 'promise', zh: '承诺' },
  { en: 'guarantee', zh: '保证' },
  { en: 'ensure', zh: '确保' },
  { en: 'confirm', zh: '确认' },
  { en: 'verify', zh: '验证' },
  { en: 'check', zh: '检查' },
  { en: 'monitor', zh: '监控' },
  { en: 'observe', zh: '观察' },
  { en: 'notice', zh: '注意' },
  { en: 'realize', zh: '意识到' },
  { en: 'recognize', zh: '认识到' },
  { en: 'identify', zh: '识别' },
  { en: 'compare', zh: '比较' },
  { en: 'connect', zh: '连接' },
  { en: 'combine', zh: '结合' },
  { en: 'merge', zh: '合并' },
  { en: 'separate', zh: '分离' },
  { en: 'divide', zh: '分开' },
  { en: 'break', zh: '打破' },
  { en: 'destroy', zh: '破坏' },
  { en: 'damage', zh: '损坏' },
  { en: 'harm', zh: '伤害' },
  { en: 'kill', zh: '杀死' },
  { en: 'die', zh: '死亡' },
  { en: 'live', zh: '生活' },
  { en: 'survive', zh: '生存' },
  { en: 'exist', zh: '存在' },
  { en: 'appear', zh: '出现' },
  { en: 'disappear', zh: '消失' },
  { en: 'occur', zh: '发生' },
  { en: 'happen', zh: '发生' },
  { en: 'take place', zh: '发生' },
  { en: 'cause', zh: '原因' },
  { en: 'lead to', zh: '导致' },
  { en: 'result in', zh: '导致' },
  { en: 'make', zh: '使' },
  { en: 'let', zh: '让' },
  { en: 'enable', zh: '使能够' },
  { en: 'prevent', zh: '防止' },
  { en: 'delay', zh: '延迟' },
  { en: 'postpone', zh: '推迟' },
  { en: 'cancel', zh: '取消' },
  { en: 'give up', zh: '放弃' },
  { en: 'quit', zh: '退出' },
  { en: 'leave', zh: '离开' },
  { en: 'enter', zh: '进入' },
  { en: 'join', zh: '加入' },
  { en: 'participate', zh: '参与' },
  { en: 'attend', zh: '参加' },
  { en: 'include', zh: '包括' },
  { en: 'contain', zh: '包含' },
  { en: 'cover', zh: '覆盖' },
  { en: 'extend', zh: '扩展' },
  { en: 'spread', zh: '传播' },
  { en: 'expand', zh: '扩大' },
  { en: 'change', zh: '改变' },
  { en: 'transform', zh: '转变' },
  { en: 'convert', zh: '转换' },
  { en: 'adapt', zh: '适应' },
  { en: 'adjust', zh: '调整' },
  { en: 'modify', zh: '修改' },
  { en: 'update', zh: '更新' },
  { en: 'replace', zh: '替换' },
  { en: 'exchange', zh: '交换' },
  { en: 'switch', zh: '切换' },
  { en: 'business', zh: '商业' },
  { en: 'industry', zh: '工业' },
  { en: 'economy', zh: '经济' },
  { en: 'finance', zh: '金融' },
  { en: 'money', zh: '钱' },
  { en: 'cash', zh: '现金' },
  { en: 'price', zh: '价格' },
  { en: 'cost', zh: '成本' },
  { en: 'value', zh: '价值' },
  { en: 'profit', zh: '利润' },
  { en: 'loss', zh: '损失' },
  { en: 'income', zh: '收入' },
  { en: 'expense', zh: '支出' },
  { en: 'investment', zh: '投资' },
  { en: 'return', zh: '回报' },
  { en: 'interest', zh: '利息' },
  { en: 'number', zh: '数字' },
  { en: 'total', zh: '总计' },
  { en: 'sum', zh: '总和' },
  { en: 'average', zh: '平均' },
  { en: 'maximum', zh: '最大' },
  { en: 'minimum', zh: '最小' },
  { en: 'size', zh: '大小' },
  { en: 'length', zh: '长度' },
  { en: 'width', zh: '宽度' },
  { en: 'height', zh: '高度' },
  { en: 'weight', zh: '重量' },
  { en: 'speed', zh: '速度' },
  { en: 'power', zh: '功率' },
  { en: 'electricity', zh: '电力' },
  { en: 'light', zh: '光' },
  { en: 'sound', zh: '声音' },
  { en: 'heat', zh: '热' },
  { en: 'temperature', zh: '温度' },
  { en: 'pressure', zh: '压力' },
  { en: 'weather', zh: '天气' },
  { en: 'environment', zh: '环境' },
  { en: 'nature', zh: '自然' },
  { en: 'world', zh: '世界' },
  { en: 'universe', zh: '宇宙' },
  { en: 'space', zh: '空间' },
  { en: 'period', zh: '时期' },
  { en: 'era', zh: '时代' },
  { en: 'history', zh: '历史' },
  { en: 'past', zh: '过去' },
  { en: 'present', zh: '现在' },
  { en: 'future', zh: '未来' },
  { en: 'modern', zh: '现代的' },
  { en: 'ancient', zh: '古代的' },
  { en: 'current', zh: '当前的' },
  { en: 'latest', zh: '最新的' },
  { en: 'recent', zh: '最近的' },
  { en: 'next', zh: '下一个' },
  { en: 'final', zh: '最终' },
  { en: 'basic', zh: '基本的' },
  { en: 'essential', zh: '必要的' },
  { en: 'key', zh: '关键的' },
  { en: 'main', zh: '主要的' },
  { en: 'primary', zh: '主要的' },
  { en: 'important', zh: '重要的' },
  { en: 'significant', zh: '显著的' },
  { en: 'excellent', zh: '优秀的' },
  { en: 'wonderful', zh: '精彩的' },
  { en: 'fantastic', zh: '极好的' },
  { en: 'amazing', zh: '令人惊讶的' },
  { en: 'incredible', zh: '难以置信的' },
  { en: 'visible', zh: '可见的' },
  { en: 'invisible', zh: '不可见的' },
  { en: 'hidden', zh: '隐藏的' },
  { en: 'secret', zh: '秘密的' },
  { en: 'private', zh: '私人的' },
  { en: 'public', zh: '公共的' },
  { en: 'open', zh: '开放的' },
  { en: 'closed', zh: '关闭的' },
  { en: 'available', zh: '可用的' },
  { en: 'unavailable', zh: '不可用的' },
  { en: 'ready', zh: '准备好的' },
  { en: 'organized', zh: '组织的' },
  { en: 'systematic', zh: '系统的' },
  { en: 'chaotic', zh: '混乱的' },
  { en: 'random', zh: '随机的' },
  { en: 'accidental', zh: '偶然的' },
  { en: 'unexpected', zh: '意外的' },
  { en: 'surprising', zh: '令人惊讶的' },
  { en: 'shocking', zh: '令人震惊的' },
  { en: 'emotional', zh: '情感的' },
  { en: 'excited', zh: '兴奋的' },
  { en: 'enthusiastic', zh: '热情的' },
  { en: 'interested', zh: '感兴趣的' },
  { en: 'curious', zh: '好奇的' },
  { en: 'anxious', zh: '焦虑的' },
  { en: 'worried', zh: '担心的' },
  { en: 'nervous', zh: '紧张的' },
  { en: 'stressed', zh: '压力大的' },
  { en: 'depressed', zh: '沮丧的' },
  { en: 'optimistic', zh: '乐观的' },
  { en: 'pessimistic', zh: '悲观的' },
  { en: 'positive', zh: '积极的' },
  { en: 'negative', zh: '消极的' },
  { en: 'neutral', zh: '中立的' },
  { en: 'professional', zh: '专业的' },
  { en: 'skilled', zh: '熟练的' },
  { en: 'expert', zh: '专家' },
  { en: 'amateur', zh: '业余的' },
  { en: 'experienced', zh: '有经验的' },
  { en: 'knowledgeable', zh: '知识渊博的' },
  { en: 'educated', zh: '受过教育的' },
  { en: 'qualified', zh: '合格的' },
  { en: 'respected', zh: '尊敬的' },
  { en: 'admired', zh: '钦佩的' },
  { en: 'popular', zh: '受欢迎的' },
  { en: 'loved', zh: '热爱的' },
  { en: 'preferred', zh: '首选的' },
  { en: 'chosen', zh: '选择的' },
  { en: 'elected', zh: '选举的' },
  { en: 'appointed', zh: '任命的' },
  { en: 'assigned', zh: '分配的' },
  { en: 'nominated', zh: '提名的' },
  { en: 'suggested', zh: '建议的' },
  { en: 'recommended', zh: '推荐的' },
  { en: 'proposed', zh: '提议的' },
  { en: 'delivered', zh: '交付的' },
  { en: 'shipped', zh: '运输的' },
  { en: 'moved', zh: '移动的' },
  { en: 'placed', zh: '放置的' },
  { en: 'located', zh: '位于的' },
  { en: 'shown', zh: '显示的' },
  { en: 'displayed', zh: '展示的' },
  { en: 'reported', zh: '报告的' },
  { en: 'announced', zh: '宣布的' },
  { en: 'declared', zh: '声明的' },
  { en: 'stated', zh: '陈述的' },
  { en: 'claimed', zh: '声称的' },
  { en: 'proven', zh: '证明的' },
  { en: 'established', zh: '建立的' },
  { en: 'founded', zh: '创立的' },
  { en: 'written', zh: '写的' },
  { en: 'typed', zh: '打字的' },
  { en: 'drawn', zh: '画的' },
  { en: 'painted', zh: '画的' },
  { en: 'decorated', zh: '装饰的' },
  { en: 'enhanced', zh: '增强的' },
  { en: 'refined', zh: '精炼的' },
  { en: 'finished', zh: '完成的' },
  { en: 'resumed', zh: '恢复的' },
  { en: 'proceeded', zh: '继续的' },
  { en: 'advanced', zh: '前进的' },
  { en: 'evolved', zh: '演变的' },
  { en: 'matured', zh: '成熟的' },
  { en: 'modernized', zh: '现代化的' },
  { en: 'renovated', zh: '翻新的' },
  { en: 'restored', zh: '恢复的' },
  { en: 'recovered', zh: '恢复的' },
  { en: 'regained', zh: '重新获得的' },
  { en: 'retrieved', zh: '取回的' },
  { en: 'saved', zh: '保存的' },
  { en: 'preserved', zh: '保存的' },
  { en: 'maintained', zh: '维护的' },
  { en: 'stored', zh: '存储的' },
  { en: 'assembled', zh: '组装的' },
  { en: 'compiled', zh: '编译的' },
  { en: 'generated', zh: '生成的' },
  { en: 'crafted', zh: '精心制作的' },
  { en: 'forged', zh: '锻造的' },
  { en: 'cast', zh: '铸造的' },
  { en: 'cut', zh: '切割的' },
  { en: 'carved', zh: '雕刻的' },
  { en: 'engraved', zh: '雕刻的' },
  { en: 'etched', zh: '蚀刻的' },
  { en: 'printed', zh: '印刷的' },
  { en: 'pressed', zh: '压制的' },
  { en: 'marked', zh: '标记的' },
  { en: 'labeled', zh: '标记的' },
  { en: 'tagged', zh: '标记的' },
  { en: 'named', zh: '命名的' },
  { en: 'titled', zh: '标题的' },
  { en: 'granted', zh: '授予的' },
  { en: 'provided', zh: '提供的' },
  { en: 'supplied', zh: '供应的' },
  { en: 'furnished', zh: '提供的' },
  { en: 'yielded', zh: '产生的' },
  { en: 'brought', zh: '带来的' },
  { en: 'adopted', zh: '采用的' },
  { en: 'followed', zh: '遵循的' },
  { en: 'practiced', zh: '实践的' },
  { en: 'applied', zh: '应用的' },
  { en: 'employed', zh: '使用的' },
  { en: 'utilized', zh: '利用的' },
  { en: 'exploited', zh: '利用的' },
  { en: 'controlled', zh: '控制的' },
  { en: 'manipulated', zh: '操纵的' },
  { en: 'governed', zh: '治理的' },
  { en: 'ruled', zh: '统治的' },
  { en: 'led', zh: '领导的' },
  { en: 'motivated', zh: '激励的' },
  { en: 'inspired', zh: '启发的' },
  { en: 'encouraged', zh: '鼓励的' },
  { en: 'supported', zh: '支持的' },
  { en: 'backed', zh: '支持的' },
  { en: 'one', zh: '一' },
  { en: 'two', zh: '二' },
  { en: 'three', zh: '三' },
  { en: 'four', zh: '四' },
  { en: 'five', zh: '五' },
  { en: 'six', zh: '六' },
  { en: 'seven', zh: '七' },
  { en: 'eight', zh: '八' },
  { en: 'nine', zh: '九' },
  { en: 'ten', zh: '十' },
  { en: 'eleven', zh: '十一' },
  { en: 'twelve', zh: '十二' },
  { en: 'thirteen', zh: '十三' },
  { en: 'fourteen', zh: '十四' },
  { en: 'fifteen', zh: '十五' },
  { en: 'sixteen', zh: '十六' },
  { en: 'seventeen', zh: '十七' },
  { en: 'eighteen', zh: '十八' },
  { en: 'nineteen', zh: '十九' },
  { en: 'twenty', zh: '二十' },
  { en: 'thirty', zh: '三十' },
  { en: 'forty', zh: '四十' },
  { en: 'fifty', zh: '五十' },
  { en: 'sixty', zh: '六十' },
  { en: 'seventy', zh: '七十' },
  { en: 'eighty', zh: '八十' },
  { en: 'ninety', zh: '九十' },
  { en: 'hundred', zh: '百' },
  { en: 'thousand', zh: '千' },
  { en: 'million', zh: '百万' },
  { en: 'billion', zh: '十亿' },
  { en: 'I', zh: '我' },
  { en: 'me', zh: '我' },
  { en: 'you', zh: '你' },
  { en: 'he', zh: '他' },
  { en: 'she', zh: '她' },
  { en: 'it', zh: '它' },
  { en: 'we', zh: '我们' },
  { en: 'us', zh: '我们' },
  { en: 'they', zh: '他们' },
  { en: 'them', zh: '他们' },
  { en: 'this is', zh: '这是' },
  { en: 'that is', zh: '那是' },
  { en: 'these are', zh: '这些是' },
  { en: 'those are', zh: '那些是' },
  { en: 'what is', zh: '是什么' },
  { en: 'who is', zh: '是谁' },
  { en: 'where is', zh: '在哪里' },
  { en: 'how is', zh: '怎么样' },
  { en: 'when is', zh: '是什么时候' },
  { en: 'why is', zh: '为什么是' },
  { en: 'I am', zh: '我是' },
  { en: 'you are', zh: '你是' },
  { en: 'he is', zh: '他是' },
  { en: 'she is', zh: '她是' },
  { en: 'it is', zh: '它是' },
  { en: 'we are', zh: '我们是' },
  { en: 'they are', zh: '他们是' },
  { en: 'I have', zh: '我有' },
  { en: 'you have', zh: '你有' },
  { en: 'he has', zh: '他有' },
  { en: 'she has', zh: '她有' },
  { en: 'it has', zh: '它有' },
  { en: 'we have', zh: '我们有' },
  { en: 'they have', zh: '他们有' },
  { en: 'I do', zh: '我做' },
  { en: 'you do', zh: '你做' },
  { en: 'he does', zh: '他做' },
  { en: 'she does', zh: '她做' },
  { en: 'it does', zh: '它做' },
  { en: 'we do', zh: '我们做' },
  { en: 'they do', zh: '他们做' },
  { en: 'I will', zh: '我会' },
  { en: 'you will', zh: '你会' },
  { en: 'he will', zh: '他会' },
  { en: 'she will', zh: '她会' },
  { en: 'it will', zh: '它会' },
  { en: 'we will', zh: '我们会' },
  { en: 'they will', zh: '他们会' },
  { en: 'I can', zh: '我能' },
  { en: 'you can', zh: '你能' },
  { en: 'he can', zh: '他能' },
  { en: 'she can', zh: '她能' },
  { en: 'it can', zh: '它能' },
  { en: 'we can', zh: '我们能' },
  { en: 'they can', zh: '他们能' },
  { en: 'I want', zh: '我想要' },
  { en: 'you want', zh: '你想要' },
  { en: 'he wants', zh: '他想要' },
  { en: 'she wants', zh: '她想要' },
  { en: 'it wants', zh: '它想要' },
  { en: 'we want', zh: '我们想要' },
  { en: 'they want', zh: '他们想要' },
  { en: 'I need', zh: '我需要' },
  { en: 'you need', zh: '你需要' },
  { en: 'he needs', zh: '他需要' },
  { en: 'she needs', zh: '她需要' },
  { en: 'it needs', zh: '它需要' },
  { en: 'we need', zh: '我们需要' },
  { en: 'they need', zh: '他们需要' },
  { en: 'I like', zh: '我喜欢' },
  { en: 'you like', zh: '你喜欢' },
  { en: 'he likes', zh: '他喜欢' },
  { en: 'she likes', zh: '她喜欢' },
  { en: 'it likes', zh: '它喜欢' },
  { en: 'we like', zh: '我们喜欢' },
  { en: 'they like', zh: '他们喜欢' },
  { en: 'I love', zh: '我爱' },
  { en: 'you love', zh: '你爱' },
  { en: 'he loves', zh: '他爱' },
  { en: 'she loves', zh: '她爱' },
  { en: 'it loves', zh: '它爱' },
  { en: 'we love', zh: '我们爱' },
  { en: 'they love', zh: '他们爱' },
  { en: 'I think', zh: '我认为' },
  { en: 'you think', zh: '你认为' },
  { en: 'he thinks', zh: '他认为' },
  { en: 'she thinks', zh: '她认为' },
  { en: 'it thinks', zh: '它认为' },
  { en: 'we think', zh: '我们认为' },
  { en: 'they think', zh: '他们认为' },
  { en: 'I know', zh: '我知道' },
  { en: 'you know', zh: '你知道' },
  { en: 'he knows', zh: '他知道' },
  { en: 'she knows', zh: '她知道' },
  { en: 'it knows', zh: '它知道' },
  { en: 'we know', zh: '我们知道' },
  { en: 'they know', zh: '他们知道' },
  { en: 'I hope', zh: '我希望' },
  { en: 'you hope', zh: '你希望' },
  { en: 'he hopes', zh: '他希望' },
  { en: 'she hopes', zh: '她希望' },
  { en: 'it hopes', zh: '它希望' },
  { en: 'we hope', zh: '我们希望' },
  { en: 'they hope', zh: '他们希望' },
  { en: 'I go', zh: '我去' },
  { en: 'you go', zh: '你去' },
  { en: 'he goes', zh: '他去' },
  { en: 'she goes', zh: '她去' },
  { en: 'it goes', zh: '它去' },
  { en: 'we go', zh: '我们去' },
  { en: 'they go', zh: '他们去' },
  { en: 'I come', zh: '我来' },
  { en: 'you come', zh: '你来' },
  { en: 'he comes', zh: '他来' },
  { en: 'she comes', zh: '她来' },
  { en: 'it comes', zh: '它来' },
  { en: 'we come', zh: '我们来' },
  { en: 'they come', zh: '他们来' },
  { en: 'I see', zh: '我看到' },
  { en: 'you see', zh: '你看到' },
  { en: 'he sees', zh: '他看到' },
  { en: 'she sees', zh: '她看到' },
  { en: 'it sees', zh: '它看到' },
  { en: 'we see', zh: '我们看到' },
  { en: 'they see', zh: '他们看到' },
  { en: 'I hear', zh: '我听到' },
  { en: 'you hear', zh: '你听到' },
  { en: 'he hears', zh: '他听到' },
  { en: 'she hears', zh: '她听到' },
  { en: 'it hears', zh: '它听到' },
  { en: 'we hear', zh: '我们听到' },
  { en: 'they hear', zh: '他们听到' },
  { en: 'I read', zh: '我阅读' },
  { en: 'you read', zh: '你阅读' },
  { en: 'he reads', zh: '他阅读' },
  { en: 'she reads', zh: '她阅读' },
  { en: 'it reads', zh: '它阅读' },
  { en: 'we read', zh: '我们阅读' },
  { en: 'they read', zh: '他们阅读' },
  { en: 'I write', zh: '我写作' },
  { en: 'you write', zh: '你写作' },
  { en: 'he writes', zh: '他写作' },
  { en: 'she writes', zh: '她写作' },
  { en: 'it writes', zh: '它写作' },
  { en: 'we write', zh: '我们写作' },
  { en: 'they write', zh: '他们写作' },
  { en: 'I eat', zh: '我吃' },
  { en: 'you eat', zh: '你吃' },
  { en: 'he eats', zh: '他吃' },
  { en: 'she eats', zh: '她吃' },
  { en: 'it eats', zh: '它吃' },
  { en: 'we eat', zh: '我们吃' },
  { en: 'they eat', zh: '他们吃' },
  { en: 'I drink', zh: '我喝' },
  { en: 'you drink', zh: '你喝' },
  { en: 'he drinks', zh: '他喝' },
  { en: 'she drinks', zh: '她喝' },
  { en: 'it drinks', zh: '它喝' },
  { en: 'we drink', zh: '我们喝' },
  { en: 'they drink', zh: '他们喝' },
  { en: 'I sleep', zh: '我睡觉' },
  { en: 'you sleep', zh: '你睡觉' },
  { en: 'he sleeps', zh: '他睡觉' },
  { en: 'she sleeps', zh: '她睡觉' },
  { en: 'it sleeps', zh: '它睡觉' },
  { en: 'we sleep', zh: '我们睡觉' },
  { en: 'they sleep', zh: '他们睡觉' },
  { en: 'I work', zh: '我工作' },
  { en: 'you work', zh: '你工作' },
  { en: 'he works', zh: '他工作' },
  { en: 'she works', zh: '她工作' },
  { en: 'it works', zh: '它工作' },
  { en: 'we work', zh: '我们工作' },
  { en: 'they work', zh: '他们工作' },
  { en: 'I study', zh: '我学习' },
  { en: 'you study', zh: '你学习' },
  { en: 'he studies', zh: '他学习' },
  { en: 'she studies', zh: '她学习' },
  { en: 'it studies', zh: '它学习' },
  { en: 'we study', zh: '我们学习' },
  { en: 'they study', zh: '他们学习' },
  { en: 'I play', zh: '我玩' },
  { en: 'you play', zh: '你玩' },
  { en: 'he plays', zh: '他玩' },
  { en: 'she plays', zh: '她玩' },
  { en: 'it plays', zh: '它玩' },
  { en: 'we play', zh: '我们玩' },
  { en: 'they play', zh: '他们玩' },
  { en: 'I learn', zh: '我学习' },
  { en: 'you learn', zh: '你学习' },
  { en: 'he learns', zh: '他学习' },
  { en: 'she learns', zh: '她学习' },
  { en: 'it learns', zh: '它学习' },
  { en: 'we learn', zh: '我们学习' },
  { en: 'they learn', zh: '他们学习' },
  { en: 'I teach', zh: '我教' },
  { en: 'you teach', zh: '你教' },
  { en: 'he teaches', zh: '他教' },
  { en: 'she teaches', zh: '她教' },
  { en: 'it teaches', zh: '它教' },
  { en: 'we teach', zh: '我们教' },
  { en: 'they teach', zh: '他们教' },
  { en: 'I help', zh: '我帮助' },
  { en: 'you help', zh: '你帮助' },
  { en: 'he helps', zh: '他帮助' },
  { en: 'she helps', zh: '她帮助' },
  { en: 'it helps', zh: '它帮助' },
  { en: 'we help', zh: '我们帮助' },
  { en: 'they help', zh: '他们帮助' },
  { en: 'I buy', zh: '我买' },
  { en: 'you buy', zh: '你买' },
  { en: 'he buys', zh: '他买' },
  { en: 'she buys', zh: '她买' },
  { en: 'it buys', zh: '它买' },
  { en: 'we buy', zh: '我们买' },
  { en: 'they buy', zh: '他们买' },
  { en: 'I sell', zh: '我卖' },
  { en: 'you sell', zh: '你卖' },
  { en: 'he sells', zh: '他卖' },
  { en: 'she sells', zh: '她卖' },
  { en: 'it sells', zh: '它卖' },
  { en: 'we sell', zh: '我们卖' },
  { en: 'they sell', zh: '他们卖' },
  { en: 'I travel', zh: '我旅行' },
  { en: 'you travel', zh: '你旅行' },
  { en: 'he travels', zh: '他旅行' },
  { en: 'she travels', zh: '她旅行' },
  { en: 'it travels', zh: '它旅行' },
  { en: 'we travel', zh: '我们旅行' },
  { en: 'they travel', zh: '他们旅行' },
  { en: 'I live', zh: '我住' },
  { en: 'you live', zh: '你住' },
  { en: 'he lives', zh: '他住' },
  { en: 'she lives', zh: '她住' },
  { en: 'it lives', zh: '它住' },
  { en: 'we live', zh: '我们住' },
  { en: 'they live', zh: '他们住' },
]

const zhToEnMap = new Map<string, string>()
const enToZhMap = new Map<string, string>()

dictionary.forEach(entry => {
  zhToEnMap.set(entry.zh, entry.en)
  enToZhMap.set(entry.en.toLowerCase(), entry.zh)
})

export interface TranslateResult {
  success: boolean
  text: string
  fromDict: boolean
}

function translateChineseToEnglish(text: string): TranslateResult {
  const trimmed = text.trim()
  
  if (zhToEnMap.has(trimmed)) {
    return { success: true, text: zhToEnMap.get(trimmed)!, fromDict: true }
  }
  
  let translated = text
  
  const reversedDict = Array.from(zhToEnMap.entries()).sort((a, b) => b[0].length - a[0].length)
  
  for (const [zh, en] of reversedDict) {
    const regex = new RegExp(`([^a-zA-Z0-9])${zh}([^a-zA-Z0-9])`, 'g')
    translated = translated.replace(regex, `$1${en}$2`)
    if (translated.startsWith(zh)) {
      const regexStart = new RegExp(`^${zh}([^a-zA-Z0-9])`)
      translated = translated.replace(regexStart, `${en}$1`)
    }
    if (translated.endsWith(zh)) {
      const regexEnd = new RegExp(`([^a-zA-Z0-9])${zh}$`)
      translated = translated.replace(regexEnd, `$1${en}`)
    }
  }
  
  const hasTranslation = translated !== text && !/^[\u4e00-\u9fa5]+$/.test(translated)
  
  return { success: hasTranslation, text: translated, fromDict: hasTranslation }
}

function translateEnglishToChinese(text: string): TranslateResult {
  const lowerText = text.toLowerCase().trim()
  
  if (enToZhMap.has(lowerText)) {
    return { success: true, text: enToZhMap.get(lowerText)!, fromDict: true }
  }
  
  let translated = text
  
  const reversedDict = Array.from(enToZhMap.entries()).sort((a, b) => b[0].length - a[0].length)
  
  for (const [en, zh] of reversedDict) {
    const regex = new RegExp(`(\\s|^|\\.|,|!|\\?)${en}(\\s|$|\\.|,|!|\\?)`, 'gi')
    translated = translated.replace(regex, `$1${zh}$2`)
  }
  
  const hasTranslation = translated !== text && /[\u4e00-\u9fa5]/.test(translated)
  
  return { success: hasTranslation, text: translated, fromDict: hasTranslation }
}

export function translateFromDict(text: string, fromLang: string, toLang: string): TranslateResult {
  if (!text || !text.trim()) {
    return { success: true, text: '', fromDict: false }
  }

  if (fromLang === 'zh' && toLang === 'en') {
    return translateChineseToEnglish(text)
  }

  if (fromLang === 'en' && toLang === 'zh') {
    return translateEnglishToChinese(text)
  }

  return { success: false, text: '', fromDict: false }
}

export function hasDictMatch(text: string, fromLang: string, toLang: string): boolean {
  if (!text || !text.trim()) return false
  
  if (fromLang === 'en' && toLang === 'zh') {
    const lowerText = text.toLowerCase().trim()
    if (enToZhMap.has(lowerText)) return true
    return Array.from(enToZhMap.keys()).some(key => text.toLowerCase().includes(key))
  }
  
  if (fromLang === 'zh' && toLang === 'en') {
    if (zhToEnMap.has(text.trim())) return true
    return Array.from(zhToEnMap.keys()).some(key => text.includes(key))
  }
  
  return false
}